<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="aspire512" name="com.puma.testscripts.Fluid_PUMA_Demo" tests="4" failures="0" timestamp="27 May 2016 04:23:27 GMT" time="2193.660" errors="3">
  <testcase name="tcPUMADemo01" time="570.293" classname="com.puma.testscripts.Fluid_PUMA_Demo"/>
  <testcase name="tcPUMADemo01" time="502.620" classname="com.puma.testscripts.Fluid_PUMA_Demo">
    <error type="java.lang.AssertionError" message="Test Failed. Order Placed not available in Order Summary Page">
      <![CDATA[java.lang.AssertionError: Test Failed. Order Placed not available in Order Summary Page
	at org.testng.Assert.fail(Assert.java:94)
	at com.ecom.support.Log.fail(Log.java:594)
	at com.ecom.support.Log.assertThat(Log.java:777)
	at com.puma.testscripts.Fluid_PUMA_Demo.tcPUMADemo01(Fluid_PUMA_Demo.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:73)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- tcPUMADemo01 -->
  <testcase name="tcPUMADemo01" time="606.400" classname="com.puma.testscripts.Fluid_PUMA_Demo">
    <error type="java.lang.AssertionError" message="Test Failed. Order Placed not available in Order Summary Page">
      <![CDATA[java.lang.AssertionError: Test Failed. Order Placed not available in Order Summary Page
	at org.testng.Assert.fail(Assert.java:94)
	at com.ecom.support.Log.fail(Log.java:594)
	at com.ecom.support.Log.assertThat(Log.java:777)
	at com.puma.testscripts.Fluid_PUMA_Demo.tcPUMADemo01(Fluid_PUMA_Demo.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:73)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- tcPUMADemo01 -->
  <testcase name="tcPUMADemo01" time="514.347" classname="com.puma.testscripts.Fluid_PUMA_Demo">
    <error type="java.lang.AssertionError" message="Test Failed. Order Placed not available in Order Summary Page">
      <![CDATA[java.lang.AssertionError: Test Failed. Order Placed not available in Order Summary Page
	at org.testng.Assert.fail(Assert.java:94)
	at com.ecom.support.Log.fail(Log.java:594)
	at com.ecom.support.Log.assertThat(Log.java:777)
	at com.puma.testscripts.Fluid_PUMA_Demo.tcPUMADemo01(Fluid_PUMA_Demo.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:73)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- tcPUMADemo01 -->
</testsuite> <!-- com.puma.testscripts.Fluid_PUMA_Demo -->
